// packages/solid/src/lib/SpawnMountPoint.tsx
import {SpawnedElement} from './SpawnedElement';
import {For, JSXElement} from 'solid-js';
import {spawned} from './internals';

/**
 * Root for all the spawned elements of the application.
 */
export function SpawnMountPoint(): JSXElement {
	return <For each={spawned()}>{(props) => <SpawnedElement {...props} />}</For>;
}

// packages/react/src/lib/SpawnMountPoint.tsx
import {useEffect, useState} from 'react';
import {SpawnedElement, SpawnedElementProps} from './SpawnedElement';
import {setSpawnedRef} from './internals';

/**
 * Root for all the spawned elements of the application.
 */
export function SpawnMountPoint(): JSX.Element {
	const [spawned, setSpawned] = useState<Array<SpawnedElementProps<unknown>>>([]);
	useEffect(() => {
		setSpawnedRef.current = setSpawned;
	}, []);
	return (
		<>
			{spawned.map((props) => (
				<SpawnedElement key={props.id} {...props} />
			))}
		</>
	);
}
