// packages/react/src/lib/AnimationWrapper.tsx
import {useCallback, useEffect, useRef, useState} from 'react';
import {AnimatedRenderer, RejectFn, ResolveFn} from './types';

export type AnimationWrapperProps<T> = {
	resolve: ResolveFn<T>;
	reject: RejectFn;
	children: AnimatedRenderer<T>;
};
export function AnimationWrapper<T>({resolve, reject, children}: AnimationWrapperProps<T>) {
	const [show, setShow] = useState(false);
	const [unmountPromiseData] = useState(() => {
		const data = {
			resolve: () => undefined as void,
			promise: null as Promise<void> | null,
		};
		data.promise = new Promise<void>((r) => (data.resolve = r));
		return data;
	});
	const internalResolve = useCallback(
		async (result: T) => {
			canUnmountRef.current = true;
			setShow(false);
			await unmountPromiseData.promise;
			resolve(result);
		},
		[resolve, unmountPromiseData.promise],
	);
	const internalReject = useCallback(
		async (err?: unknown) => {
			canUnmountRef.current = true;
			setShow(false);
			await unmountPromiseData.promise;
			reject(err);
		},
		[reject, unmountPromiseData.promise],
	);
	const unmount = useCallback(() => {
		if (canUnmountRef.current) {
			unmountPromiseData.resolve();
		}
	}, [unmountPromiseData]);
	const canUnmountRef = useRef(false);
	useEffect(() => {
		const frameId = requestAnimationFrame(() => {
			setShow(true);
		});
		return () => cancelAnimationFrame(frameId);
	}, []);
	return <>{children(internalResolve, internalReject, unmount, show)}</>;
}

// packages/solid/src/lib/AnimationWrapper.tsx
import {createSignal, onCleanup, onMount} from 'solid-js';
import {AnimatedRenderer, RejectFn, ResolveFn} from './types';

export type AnimationWrapperProps<T> = {
	resolve: ResolveFn<T>;
	reject: RejectFn;
	children: AnimatedRenderer<T>;
};

/**
 * Internal wrapper for spawnAnimate that allows a delay before unmounting the component
 */
export function AnimationWrapper<T>(props: AnimationWrapperProps<T>) {
	const [show, setShow] = createSignal(false);
	let canUnmount = false;
	const unmountPromiseData = (() => {
		const data = {
			resolve: () => undefined as void,
			promise: null as Promise<void> | null,
		};
		data.promise = new Promise<void>((r) => (data.resolve = r));
		return data;
	})();
	async function internalResolve(result: T) {
		canUnmount = true;
		setShow(false);
		await unmountPromiseData.promise;
		props.resolve(result);
	}
	async function internalReject(err?: unknown) {
		canUnmount = true;
		setShow(false);
		await unmountPromiseData.promise;
		props.reject(err);
	}
	function unmount() {
		if (canUnmount) {
			unmountPromiseData.resolve();
		}
	}
	let frameId: number | undefined = undefined;
	onMount(() => {
		frameId = requestAnimationFrame(() => {
			setShow(true);
		});
	});
	onCleanup(() => {
		if (frameId !== undefined) {
			cancelAnimationFrame(frameId);
		}
	});
	return <>{props.children(internalResolve, internalReject, unmount, show)}</>;
}
